workflows:
  macOS-workflow-arm:
    name: macOS Workflow ARM
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: 15
      cocoapods: default
      node: 18.17.0
    triggering:
      events:
        - push
    scripts:
      - name: Install Golang
        script: |
          curl -fLO https://go.dev/dl/go1.20.7.darwin-arm64.pkg
          echo $PWD
          sudo installer -pkg go1.20.7.darwin-arm64.pkg -target /
      - name: 安装依赖 && 编译
        script: |
          echo $(uname -a)
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          ROOT=$(pwd)
          mkdir -p ${ROOT}/build/bin
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy

          cd ${ROOT}/frontend
          npm install

          cd ${ROOT}/thirdparty
          pip install -r requirements.txt
          pyinstaller -F -w pdf.py
          cp dist/pdf ${ROOT}/build/bin/
          cp ocr.py convert_external.py ${ROOT}/build/bin/
          
          cd $ROOT
          wails build -ldflags "-s -w"
    artifacts:
      - build/bin
    publishing:
      email:
        recipients:
          - kevin2li@qq.com
